---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: openclaw-xpd-files
  namespace: default
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 50Gi
  storageClassName: ceph-application-high-performance
